# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: "Install Packages for the Backend"
  inputs:
    command: 'custom'
    customCommand: 'install'
    workingDir: 'back-end'
- task: Npm@1
  displayName: "Install Packages for the Frontend"
  inputs:
    command: 'install'
    workingDir: 'front-end'
- task: Npm@1
  displayName: " Packages for the Frontend"
  inputs:
    command: 'install'
    workingDir: 'front-end'
    customCommand: 'run build'

- task: CopyFiles@2
  inputs:
    Contents: |
      front-end/dist/**
      back-end/**
    TargetFolder: $(Build.ArtifactStagingDirectory)
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'release'
    publishLocation: 'Container'